### ISSUE TITLE
Events array should include action

### ISSUE THREAD

**Issue by timwis** [CodeForPhilly/stately#10]
So that the history panel can say "Tim Wisniewski - Initiate - 3pm"

**Comment by mjumbewu** [comment]
I added a `slug` to `Action`, which should be used in the URL. So, how about we return `"action"` as an object `{"name", "slug"}`. This is the way it's implemented in commit af5e3bb. Seem reasonable? I can't think of any reason we need the slug once the event is created, so it may be extraneous info for now,  and should arguably be the string that is the name.

**Comment by timwis** [comment]
That sounds great
