### ISSUE TITLE
Initiate event has null actor

### ISSUE THREAD

**Issue by timwis** [CodeForPhilly/stately#11]
I can see why this is: There was no token because it's a public form. Just trying to think of what to show in the case history. Perhaps just "Initiated". Unless we have a better idea.

**Comment by mjumbewu** [comment]
Yeah, I'm thinking just "initiated". This is where the verification step would come in to play. Until we have an authenticated user (either by some explicit password or implicitly by token attached to email address) then we can't attribute actions taken by that user to anyone. So, I'd think in the case history we'd see:
- Initiated - 3 pm
- Mjumbe Poe - Verified - 3:30 pm
- Tim Wisniewski - Approved - 5 pm
- ...

Another possibility is that we could "rewrite history" in the case of the first event, if we make the verification step a first-class idea and not just the same as any other type of action. I.e., the event would start off as anonymous, but the actor would get assigned after being verified. Or maybe the actor is assigned immediately, but with an explicit `verified = False` flag.

And maybe that's the right way to go, but I don't think it is for v1.

**Comment by timwis** [comment]
Yeah that makes sense. The only thing is, for workflows that don't involve email verification of the initiator, the history won't say who initiated it. But yeah, we can solve this one later.
