### ISSUE TITLE
Event should not be created if handler fails

### ISSUE THREAD

**Issue by timwis** [CodeForPhilly/stately#15]
@mjumbewu I've noticed that if the event handler fails due to some kind of error in the handler code, the event is still created. I think one would expect the event only to be created if the handler works. This would also be necessary functionality if we want handlers to be able to abort events (ie. if some condition is not met).

I think the order of [these lines](https://github.com/CodeForPhilly/stately/blob/master/server/src/stately/views.py#L176-L177) (or lack of dependency on one another) is the cause.

**Comment by mjumbewu** [comment]
Yup. What maybe should happen here is that `create_event` should instantiate an `Event`, but not save it to the database. The save should come after the event is handled.

Though, a tricky but is that we also do things like create `Assignment` objects and send emails in these handlers. We could just wrap the whole thing in a DB transaction that will roll back on error, which is easy enough, but wouldn't undo any emails sent. We might need to queue any messages and send them on handler success.

**Comment by timwis** [comment]
Should we close this in favor of #29?

**Comment by mjumbewu** [comment]
This isn't quite handled by #29. In commit bfe44f2 we wrap the event in a transaction so that if the handler fails the database gets rolled back to before the event was created.
