### ISSUE TITLE
Allow cookies in CORS requests

### ISSUE THREAD

**Issue by mjumbewu** [CodeForPhilly/stately#19]
Requests that use CORS must set `withCredentials` on the `XmlHttpRequest` object to use cookies (e.g., for sessions). Does choo's `http` have a simple way of patching the XHR object?

More info: https://quickleft.com/blog/cookies-with-my-cors/

**Comment by timwis** [comment]
Yep, choo's [http](https://github.com/yoshuawuyts/choo/blob/master/http.js) is really just the [xhr](https://github.com/naugtur/xhr) lib, which allows `withCredentials: true` in the options.

**Comment by timwis** [comment]
From xhr docs:

> A wildcard \* cannot be used in the Access-Control-Allow-Origin header when withCredentials is true. The header needs to specify your origin explicitly or browser will abort the request.

I recall running into this with another project. The server should be able to respond with `Access-Control-Allow-Origin` set to whatever origin is making the request, dynamically.

EDIT: Fixed with `CORS_ALLOW_CREDENTIALS = True`
