### ISSUE TITLE
send_email vs assign

### ISSUE THREAD

**Issue by timwis** [CodeForPhilly/stately#2]
I'd like to suggest that we generate tokens via something like `assign(email)` instead of `send_email(email)`. In the case of indebtedness, there are so many new entries, even in batches at a time, that the reviewers prefer not to get an email for each one but would rather just have an inbox of things awaiting their review. Something like:

``` python
token = assign(email)
send_email(email, token)
```

or

``` python
assign(email, send_email=True)
```

or something like that. I suppose `send_email()` could _call_ `assign()` as a side effect too..

Note that I'm using the word `assign` instead of `generate_token` because if you think about token records in the context of #1, they're more than just tokens; they're more like "access."

**Comment by mjumbewu** [comment]
Yup, `assign` definitely seems like the right way to think about it. In fact, the `Actor` model we have now should really be `Assignment`. I pushed up a new branch where this change is made. It included a migration.  If you want to try it out, run:

``` bash
# migrate the db
src/manage.py migrate stately
# the workflows had to change, with the new function names, so reload them
src/manage.py workflow_drop $(src/manage.py workflow_list)
src/manage.py workflow_load ../workflows/*
```
