### ISSUE TITLE
Sign-in functionality

### ISSUE THREAD

**Issue by timwis** [CodeForPhilly/stately#33]
In order to get to inboxes

`/signin` sends a verification email
`/verify` sets a session, which contains your email address in the data so it can be shown in the UI
(route names are just suggestions)

Routes can simply return successful status codes or an error.

Unfortunately this introduces another type of token. #36 may consolidate.

**Comment by mjumbewu** [comment]
The API will have two routes:

`/send-auth-token`, which takes `{email: 'my@email.com'}` and returns `204 NO CONTENT` on success
`/authenticate?token=...`, which returns `204 NO CONTENT` on success

**Comment by timwis** [comment]
UI should be done in 4588b72, so close this issue once you're finished on the api
