### ISSUE TITLE
List cases awaiting your action

### ISSUE THREAD

**Issue by timwis** [CodeForPhilly/stately#35]
An "inbox" showing cases which are assigned to you that you have not acted on yet and are currently in the state that you're assigned to.

Edge cases:
- Cathy and Anna are both Deputy Finance Directors. Contracts can be approved by either of them during the "Awaiting Finance Approval" state.
- Indebtedness: 2 of the 3 reviewers can submit their action before the state changes

Note: these cases will be covered by #34, so this is less MVP than that one.

**Comment by timwis** [comment]
Note that the current `/cases/awaiting` endpoint does not return any assignment tokens with each case. The property is there but it's always null.

**Comment by mjumbewu** [comment]
I'm considering adding an `is_valid` field to `Assignment` instances. So, in the case where Cathy and Anna are both Deputy Finance Directors, when one acts on their assignment, the other's assignment would get `is_valid` set to `False` -- perhaps explicitly in the handler, perhaps automatically as a consequence of the case transitioning out of the assigned state with no action taken on the assignment. Probably the latter.

Does that seem reasonable? If the case transitions to another state, then all incomplete assignments are simply marked as invalid?

**Comment by timwis** [comment]
@mjumbewu maybe I'm misunderstanding, but I'm not sure that's necessary. If the `/cases/awaiting/` endpoint queries cases that (a) are assigned to you, (b) you haven't acted on yet, and (c) the case is currently in the _state_ you're assigned to -- it should handle both scenarios described above, no?

**Comment by timwis** [comment]
Since this feature has been implemented, I'll close this MVP issue and have copied the `is_valid` discussion into #52 for further conversation.
