### ISSUE TITLE
Seed database with sample data

### ISSUE THREAD

**Issue by timwis** [CodeForPhilly/stately#4]
At least a sample workflow for development purposes. It looks like this was begun with `load_from_config_file` in `models.py` but I don't see it being used anywhere else in the project. Is it meant to be used from the REPL or something?

**Comment by timwis** [comment]
I think I figured it out. Will update docs.

**Comment by mjumbewu** [comment]
I added (and documented) a few management commands in commit 9e5ba60 to help with this:

``` bash
$ src/manage.py
# 
# Type 'manage.py help <subcommand>' for help on a specific subcommand.
# 
# Available subcommands:
# 
# [django]
#     ...
# 
# [stately]
#     workflow_drop
#     workflow_list
#     workflow_load

$ src/manage.py workflow_load ../workflows/*
# Loading workflow from ../workflows/indebtedness.yml
# Loading workflow from ../workflows/travel-request.yml

$ src/manage.py workflow_list
# indebtedness
# travel-request
```

**Comment by timwis** [comment]
Even better! Nice
