### ISSUE TITLE
A signed in user can put someone else's email in "submitter email" field

### ISSUE THREAD

**Issue by timwis** [CodeForPhilly/stately#41]
This skips email verification because the user is authenticated. The case history will show the true user, but the case data will show whatever email was typed in. Not sure the best way to resolve this.

**Comment by mjumbewu** [comment]
@timwis We could say `if actor and actor.email == data.submitter_email`. If it's not equal we could either go to the verification step anyway or `raise error`.

**Comment by mjumbewu** [comment]
I pushed up a change to the travel request form that demonstrates the above comment. This may be sufficient if we address issue #38.

**Comment by timwis** [comment]
good thinking. LGTM!
