### ISSUE TITLE
Anonymous session is unauthorized

### ISSUE THREAD

**Issue by timwis** [CodeForPhilly/stately#50]
Per slack:

> if you create a case as anonymous user, it does set a session, but if you try to hit refresh, it throws a `403` `invalid actor token` error. the session cookie does appear to be there though.
> /Cc @mjumbewu

**Comment by mjumbewu** [comment]
@timwis you're still seeing this? I am not able to replicate. What I see happening is that `/actor` replies with a 200, but `null` in the body (which is ok, because the token is still set on the session cookie). However, the UI does not then make a request for the case (because `null` actor?).

**Comment by timwis** [comment]
@mjumbewu yes I'm still seeing this. To reproduce, pull down the latest code and submit a travel request from an incognito window. Once you submit, you'll get an infinite loop of failed requests (which is an issue), so just hit the back button to make it stop, then you can inspect one of the failed requests and see the `403` error, along with the session that _is_ set.

Note I'm talking about the case request, not the `/actor` request.
